const alojamientos = [
	{
		ciudad: 'Buenos Aires',
		nombre: 'Hotel Boutique Palermo',
		facilidades: ['WiFi', 'Television', 'Desayuno'],
		tipoAlojamiento: 'Hotel',
		ubicacion: 'Cerca del aeropuerto',
		cantidadPersonas: 2,
		precio: 100,
	},
	{
		ciudad: 'Buenos Aires',
		nombre: 'Departamento Recoleta',
		facilidades: ['WiFi', 'Calefaccion', 'Lavarropas'],
		tipoAlojamiento: 'Departamento',
		ubicacion: 'En el centro',
		cantidadPersonas: 3,
		precio: 80,
	},
	{
		ciudad: 'Buenos Aires',
		nombre: 'Casa en San Telmo',
		facilidades: ['WiFi', 'Aire acondicionado', 'Estacionamiento'],
		tipoAlojamiento: 'Casa',
		ubicacion: 'A las afueras',
		cantidadPersonas: 5,
		precio: 120,
	},
	{
		ciudad: 'Buenos Aires',
		nombre: 'Quinta en Tigre',
		facilidades: ['Pileta', 'Calefaccion', 'Television'],
		tipoAlojamiento: 'Quinta',
		ubicacion: 'En el campo',
		cantidadPersonas: 6,
		precio: 150,
	},
	{
		ciudad: 'Buenos Aires',
		nombre: 'Cabaña Ecológica',
		facilidades: ['Calefaccion', 'Lavarropas', 'Pileta'],
		tipoAlojamiento: 'Cabaña',
		ubicacion: 'En la montaña',
		cantidadPersonas: 4,
		precio: 90,
	},
	{
		ciudad: 'Cordoba',
		nombre: 'Departamento en Nueva Córdoba',
		facilidades: ['WiFi', 'Television', 'Desayuno'],
		tipoAlojamiento: 'Departamento',
		ubicacion: 'En el centro',
		cantidadPersonas: 3,
		precio: 85,
	},
	{
		ciudad: 'Cordoba',
		nombre: 'Hotel Serrano',
		facilidades: ['Aire acondicionado', 'Television', 'Estacionamiento'],
		tipoAlojamiento: 'Hotel',
		ubicacion: 'En la montaña',
		cantidadPersonas: 2,
		precio: 95,
	},
	{
		ciudad: 'Cordoba',
		nombre: 'Casa con pileta',
		facilidades: ['Pileta', 'WiFi', 'Lavarropas'],
		tipoAlojamiento: 'Casa',
		ubicacion: 'A las afueras',
		cantidadPersonas: 5,
		precio: 110,
	},
	{
		ciudad: 'Cordoba',
		nombre: 'Quinta El Paraiso',
		facilidades: ['Estacionamiento', 'Television', 'Calefaccion'],
		tipoAlojamiento: 'Quinta',
		ubicacion: 'En el campo',
		cantidadPersonas: 6,
		precio: 130,
	},
	{
		ciudad: 'Cordoba',
		nombre: 'Cabaña La Soñada',
		facilidades: ['WiFi', 'Calefaccion', 'Pileta'],
		tipoAlojamiento: 'Cabaña',
		ubicacion: 'En la montaña',
		cantidadPersonas: 4,
		precio: 100,
	},
	{
		ciudad: 'Rosario',
		nombre: 'Hotel En el centro',
		facilidades: ['Desayuno', 'Television', 'WiFi'],
		tipoAlojamiento: 'Hotel',
		ubicacion: 'En el centro',
		cantidadPersonas: 2,
		precio: 90,
	},
	{
		ciudad: 'Rosario',
		nombre: 'Departamento Vista Río',
		facilidades: ['WiFi', 'Calefaccion', 'Aire acondicionado'],
		tipoAlojamiento: 'Departamento',
		ubicacion: 'En el centro',
		cantidadPersonas: 3,
		precio: 85,
	},
	{
		ciudad: 'Rosario',
		nombre: 'Casa en el barrio Alberdi',
		facilidades: ['Television', 'Lavarropas', 'Estacionamiento'],
		tipoAlojamiento: 'Casa',
		ubicacion: 'A las afueras',
		cantidadPersonas: 5,
		precio: 105,
	},
	{
		ciudad: 'Rosario',
		nombre: 'Quinta Las Palmeras',
		facilidades: ['Pileta', 'Estacionamiento', 'WiFi'],
		tipoAlojamiento: 'Quinta',
		ubicacion: 'En el campo',
		cantidadPersonas: 6,
		precio: 140,
	},
	{
		ciudad: 'Rosario',
		nombre: 'Cabaña La Paz',
		facilidades: ['Calefaccion', 'Pileta', 'Television'],
		tipoAlojamiento: 'Cabaña',
		ubicacion: 'En la montaña',
		cantidadPersonas: 4,
		precio: 95,
	},
	{
		ciudad: 'Santa Fe',
		nombre: 'Hotel Colonial',
		facilidades: ['WiFi', 'Television', 'Desayuno'],
		tipoAlojamiento: 'Hotel',
		ubicacion: 'En el centro',
		cantidadPersonas: 2,
		precio: 100,
	},
	{
		ciudad: 'Santa Fe',
		nombre: 'Departamento en Bulevar',
		facilidades: ['Calefaccion', 'Aire acondicionado', 'Lavarropas'],
		tipoAlojamiento: 'Departamento',
		ubicacion: 'En el centro',
		cantidadPersonas: 3,
		precio: 80,
	},
	{
		ciudad: 'Santa Fe',
		nombre: 'Casa Quinta',
		facilidades: ['Pileta', 'Estacionamiento', 'Television'],
		tipoAlojamiento: 'Casa',
		ubicacion: 'En el campo',
		cantidadPersonas: 5,
		precio: 110,
	},
	{
		ciudad: 'Santa Fe',
		nombre: 'Quinta El Encuentro',
		facilidades: ['WiFi', 'Calefaccion', 'Desayuno'],
		tipoAlojamiento: 'Quinta',
		ubicacion: 'En el campo',
		cantidadPersonas: 6,
		precio: 130,
	},
	{
		ciudad: 'Santa Fe',
		nombre: 'Cabaña La Esperanza',
		facilidades: ['Pileta', 'WiFi', 'Television'],
		tipoAlojamiento: 'Cabaña',
		ubicacion: 'En la montaña',
		cantidadPersonas: 4,
		precio: 90,
	},
	// Nuevos alojamientos cerca de la playa
	{
		ciudad: 'Mar del Plata',
		nombre: 'Hotel Playa Grande',
		facilidades: ['WiFi', 'Desayuno', 'Estacionamiento'],
		tipoAlojamiento: 'Hotel',
		ubicacion: 'En la zona de playa',
		cantidadPersonas: 2,
		precio: 120,
	},
	{
		ciudad: 'Mar del Plata',
		nombre: 'Departamento Frente al Mar',
		facilidades: ['WiFi', 'Calefaccion', 'Aire acondicionado'],
		tipoAlojamiento: 'Departamento',
		ubicacion: 'En la zona de playa',
		cantidadPersonas: 4,
		precio: 150,
	},
	{
		ciudad: 'Pinamar',
		nombre: 'Casa Costa Atlántica',
		facilidades: ['Pileta', 'WiFi', 'Television'],
		tipoAlojamiento: 'Casa',
		ubicacion: 'En la zona de playa',
		cantidadPersonas: 6,
		precio: 200,
	},
	{
		ciudad: 'Pinamar',
		nombre: 'Cabaña de Madera',
		facilidades: ['Calefaccion', 'Television', 'Pileta'],
		tipoAlojamiento: 'Cabaña',
		ubicacion: 'En la zona de playa',
		cantidadPersonas: 4,
		precio: 130,
	},
];

export default alojamientos;

