const alojamientos = [
	{
		ciudad: 'Buenos Aires',
		nombre: 'Hotel Boutique Palermo',
		facilidades: ['WiFi', 'Television', 'Desayuno'],
		tipoAlojamiento: 'Hotel',
		ubicacion: 'Centro',
		cantidadPersonas: 2,
	},
	{
		ciudad: 'Buenos Aires',
		nombre: 'Departamento Recoleta',
		facilidades: ['WiFi', 'Calefaccion', 'Lavarropas'],
		tipoAlojamiento: 'Departamento',
		ubicacion: 'Centro',
		cantidadPersonas: 3,
	},
	{
		ciudad: 'Buenos Aires',
		nombre: 'Casa en San Telmo',
		facilidades: ['WiFi', 'Aire acondicionado', 'Estacionamiento'],
		tipoAlojamiento: 'Casa',
		ubicacion: 'A las afueras',
		cantidadPersonas: 5,
	},
	{
		ciudad: 'Buenos Aires',
		nombre: 'Quinta en Tigre',
		facilidades: ['Pileta', 'Calefaccion', 'Television'],
		tipoAlojamiento: 'Quinta',
		ubicacion: 'Campo',
		cantidadPersonas: 6,
	},
	{
		ciudad: 'Buenos Aires',
		nombre: 'Cabaña Ecológica',
		facilidades: ['Calefaccion', 'Lavarropas', 'Pileta'],
		tipoAlojamiento: 'Cabaña',
		ubicacion: 'Montaña',
		cantidadPersonas: 4,
	},
	{
		ciudad: 'Cordoba',
		nombre: 'Departamento en Nueva Córdoba',
		facilidades: ['WiFi', 'Television', 'Desayuno'],
		tipoAlojamiento: 'Departamento',
		ubicacion: 'Centro',
		cantidadPersonas: 3,
	},
	{
		ciudad: 'Cordoba',
		nombre: 'Hotel Serrano',
		facilidades: ['Aire acondicionado', 'Television', 'Estacionamiento'],
		tipoAlojamiento: 'Hotel',
		ubicacion: 'Montaña',
		cantidadPersonas: 2,
	},
	{
		ciudad: 'Cordoba',
		nombre: 'Casa con pileta',
		facilidades: ['Pileta', 'WiFi', 'Lavarropas'],
		tipoAlojamiento: 'Casa',
		ubicacion: 'A las afueras',
		cantidadPersonas: 5,
	},
	{
		ciudad: 'Cordoba',
		nombre: 'Quinta El Paraiso',
		facilidades: ['Estacionamiento', 'Television', 'Calefaccion'],
		tipoAlojamiento: 'Quinta',
		ubicacion: 'Campo',
		cantidadPersonas: 6,
	},
	{
		ciudad: 'Cordoba',
		nombre: 'Cabaña La Soñada',
		facilidades: ['WiFi', 'Calefaccion', 'Pileta'],
		tipoAlojamiento: 'Cabaña',
		ubicacion: 'Montaña',
		cantidadPersonas: 4,
	},
	{
		ciudad: 'Rosario',
		nombre: 'Hotel Centro',
		facilidades: ['Desayuno', 'Television', 'WiFi'],
		tipoAlojamiento: 'Hotel',
		ubicacion: 'Centro',
		cantidadPersonas: 2,
	},
	{
		ciudad: 'Rosario',
		nombre: 'Departamento Vista Río',
		facilidades: ['WiFi', 'Calefaccion', 'Aire acondicionado'],
		tipoAlojamiento: 'Departamento',
		ubicacion: 'Centro',
		cantidadPersonas: 3,
	},
	{
		ciudad: 'Rosario',
		nombre: 'Casa en el barrio Alberdi',
		facilidades: ['Television', 'Lavarropas', 'Estacionamiento'],
		tipoAlojamiento: 'Casa',
		ubicacion: 'A las afueras',
		cantidadPersonas: 5,
	},
	{
		ciudad: 'Rosario',
		nombre: 'Quinta Las Palmeras',
		facilidades: ['Pileta', 'Estacionamiento', 'WiFi'],
		tipoAlojamiento: 'Quinta',
		ubicacion: 'Campo',
		cantidadPersonas: 6,
	},
	{
		ciudad: 'Rosario',
		nombre: 'Cabaña La Paz',
		facilidades: ['Calefaccion', 'Pileta', 'Television'],
		tipoAlojamiento: 'Cabaña',
		ubicacion: 'Montaña',
		cantidadPersonas: 4,
	},
	{
		ciudad: 'Santa Fe',
		nombre: 'Hotel Colonial',
		facilidades: ['WiFi', 'Television', 'Desayuno'],
		tipoAlojamiento: 'Hotel',
		ubicacion: 'Centro',
		cantidadPersonas: 2,
	},
	{
		ciudad: 'Santa Fe',
		nombre: 'Departamento en Bulevar',
		facilidades: ['Calefaccion', 'Aire acondicionado', 'Lavarropas'],
		tipoAlojamiento: 'Departamento',
		ubicacion: 'Centro',
		cantidadPersonas: 3,
	},
	{
		ciudad: 'Santa Fe',
		nombre: 'Casa Quinta',
		facilidades: ['Pileta', 'Estacionamiento', 'Television'],
		tipoAlojamiento: 'Casa',
		ubicacion: 'Campo',
		cantidadPersonas: 5,
	},
	{
		ciudad: 'Santa Fe',
		nombre: 'Quinta El Encuentro',
		facilidades: ['WiFi', 'Calefaccion', 'Desayuno'],
		tipoAlojamiento: 'Quinta',
		ubicacion: 'Campo',
		cantidadPersonas: 6,
	},
	{
		ciudad: 'Santa Fe',
		nombre: 'Cabaña La Esperanza',
		facilidades: ['Pileta', 'WiFi', 'Television'],
		tipoAlojamiento: 'Cabaña',
		ubicacion: 'Montaña',
		cantidadPersonas: 4,
	},
];

export default alojamientos;

